-- Update PROJECT_ID and DEST_DATASET before running
CREATE OR REPLACE TABLE `PROJECT_ID.DEST_DATASET.ga4_flat_events` AS
SELECT
    -- identifiers
    event_date,
    event_name,
    event_timestamp,
    event_bundle_sequence_id,
    event_value_in_usd,
    user_pseudo_id,
    user_first_touch_timestamp,
    stream_id,
    platform,
    -- privacy
    privacy_info.uses_transient_token,
    -- device
    device.category AS device_category,
    device.mobile_brand_name AS device_mobile_brand,
    device.mobile_model_name AS device_mobile_model,
    device.mobile_marketing_name AS device_mobile_marketing,
    device.operating_system AS device_os,
    device.operating_system_version AS device_os_version,
    device.language AS device_language,
    device.is_limited_ad_tracking AS device_limited_ad_tracking,
    device.web_info.browser AS browser,
    device.web_info.browser_version AS browser_version,
    -- geo
    geo.continent,
    geo.country,
    geo.region,
    geo.city,
    geo.sub_continent,
    geo.metro,
    -- traffic_source (first touch)
    traffic_source.source AS traffic_source,
    traffic_source.medium AS traffic_medium,
    traffic_source.name AS traffic_campaign,
    -- ecommerce
    ecommerce.total_item_quantity AS ecom_total_item_qty,
    ecommerce.purchase_revenue_in_usd AS ecom_revenue_usd,
    ecommerce.purchase_revenue AS ecom_revenue,
    ecommerce.tax_value_in_usd AS ecom_tax_usd,
    ecommerce.tax_value AS ecom_tax,
    ecommerce.unique_items AS ecom_unique_items,
    ecommerce.transaction_id AS ecom_transaction_id,
    -- event_params (24 keys)
    (SELECT MAX(value.string_value) FROM UNNEST(event_params) WHERE key = 'page_location') AS page_location,
    (SELECT MAX(value.string_value) FROM UNNEST(event_params) WHERE key = 'page_title') AS page_title,
    (SELECT MAX(value.string_value) FROM UNNEST(event_params) WHERE key = 'page_referrer') AS page_referrer,
    (SELECT MAX(value.string_value) FROM UNNEST(event_params) WHERE key = 'source') AS ep_source,
    (SELECT MAX(value.string_value) FROM UNNEST(event_params) WHERE key = 'medium') AS ep_medium,
    (SELECT MAX(value.string_value) FROM UNNEST(event_params) WHERE key = 'campaign') AS ep_campaign,
    (SELECT MAX(value.string_value) FROM UNNEST(event_params) WHERE key = 'term') AS ep_term,
    (SELECT MAX(value.int_value) FROM UNNEST(event_params) WHERE key = 'ga_session_id') AS ga_session_id,
    (SELECT MAX(value.int_value) FROM UNNEST(event_params) WHERE key = 'ga_session_number') AS ga_session_number,
    (SELECT MAX(value.int_value) FROM UNNEST(event_params) WHERE key = 'engagement_time_msec') AS engagement_time_msec,
    (SELECT MAX(value.int_value) FROM UNNEST(event_params) WHERE key = 'entrances') AS entrances,
    (SELECT MAX(value.int_value) FROM UNNEST(event_params) WHERE key = 'debug_mode') AS debug_mode,
    (SELECT MAX(value.int_value) FROM UNNEST(event_params) WHERE key = 'engaged_session_event') AS engaged_session_event,
    (SELECT MAX(COALESCE(value.string_value, CAST(value.int_value AS STRING))) FROM UNNEST(event_params) WHERE key = 'session_engaged') AS session_engaged,
    (SELECT MAX(value.string_value) FROM UNNEST(event_params) WHERE key = 'clean_event') AS clean_event,
    (SELECT MAX(value.string_value) FROM UNNEST(event_params) WHERE key = 'link_domain') AS link_domain,
    (SELECT MAX(value.string_value) FROM UNNEST(event_params) WHERE key = 'link_url') AS link_url,
    (SELECT MAX(COALESCE(value.string_value, CAST(value.int_value AS STRING), CAST(value.float_value AS STRING), CAST(value.double_value AS STRING)))
     FROM UNNEST(event_params) WHERE key = 'outbound') AS outbound,
    (SELECT MAX(value.int_value) FROM UNNEST(event_params) WHERE key = 'percent_scrolled') AS percent_scrolled,
    (SELECT MAX(value.string_value) FROM UNNEST(event_params) WHERE key = 'search_term') AS search_term,
    (SELECT MAX(value.int_value) FROM UNNEST(event_params) WHERE key = 'unique_search_term') AS unique_search_term,
    (SELECT MAX(value.string_value) FROM UNNEST(event_params) WHERE key = 'promotion_name') AS ep_promotion_name,
    (SELECT MAX(value.string_value) FROM UNNEST(event_params) WHERE key = 'coupon') AS ep_coupon,
    (SELECT MAX(value.string_value) FROM UNNEST(event_params) WHERE key = 'currency') AS ep_currency
FROM `bigquery-public-data.ga4_obfuscated_sample_ecommerce.events_*`;
